name = "vip-video-player"
main = "./workers-site/index.js"
compatibility_date = "2024-04-08"
account_id = "a44b12c63b3be31c1566b8da6b159544"

[site]
bucket = "./dist"

[build]
command = "npm run build"

[[kv_namespaces]]
binding = "ASSETS"
id = "61147c96a1864b29ae12f59f10f8bca1"
