name = "vip-video-player"
type = "webpack"
account_id = ""  # 你的 Cloudflare 账户 ID
workers_dev = true
route = ""
zone_id = ""

[site]
bucket = "dist"
entry-point = "workers-site"

[env.production]
workers_dev = false

[build]
command = "npm run build" 